// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snotxicwhpivolqygtze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNub3R4aWN3aHBpdm9scXlndHplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODc1MzQsImV4cCI6MjA3MTM2MzUzNH0.jQZRKKk7yunbygeulomj7xF-B7q8vWwaUdybFMAFOKM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});